const fs = require('fs');
let code = fs.readFileSync('src/App.tsx', 'utf-8');
code = code.replace(/adhd-waste-logs-v1/g, 'friction-logs-v1');
code = code.replace(/WasteLog/g, 'FrictionLog');
code = code.replace(/wasteData/g, 'frictionData');
code = code.replace(/setWasteData/g, 'setFrictionData');
code = code.replace(/isWasteLogOpen/g, 'isFrictionLogOpen');
code = code.replace(/setIsWasteLogOpen/g, 'setIsFrictionLogOpen');
code = code.replace(/dayWasteLogs/g, 'dayFrictionLogs');
code = code.replace(/parseWasteDuration/g, 'parseFrictionDuration');
code = code.replace(/addWasteLog/g, 'addFrictionLog');
code = code.replace(/deleteWasteLog/g, 'deleteFrictionLog');
code = code.replace(/'wasted'/g, "'friction'");
code = code.replace(/Wasted Time/g, "Friction");
code = code.replace(/Waste Log/g, "Friction Log");
code = code.replace(/timeWasted/g, 'timeLost');
code = code.replace(/Log Waste/g, 'Log Friction');
code = code.replace(/>Wasted</g, '>Friction<');
code = code.replace(/Wasted/g, 'Friction');
fs.writeFileSync('src/App.tsx', code);
console.log('Replacements done');
